"""empty message

Revision ID: 8c0bf8b9b00d
Revises: 290ed54c4585
Create Date: 2024-09-03 09:14:28.488914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0bf8b9b00d'
down_revision = '290ed54c4585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pago_stripe_id', sa.String(length=250), nullable=False))
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('pago_stripe_id')

    # ### end Alembic commands ###
