"""empty message

Revision ID: 90d2a192d5b6
Revises: d53c38260d2b
Create Date: 2024-09-03 01:47:28.496611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d2a192d5b6'
down_revision = 'd53c38260d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
